import React, { useState, useEffect } from 'react'
import Layout from '../shared/Layout'
import Button from '../ui/Button'
import { supabase } from '../../lib/supabaseClient'

export default function Notifications({ onNavigate, user }) {
  const [loading, setLoading] = useState(true)
  const [household, setHousehold] = useState(null)
  const [alerts, setAlerts] = useState([])

  useEffect(() => {
    const fetchData = async () => {
      try {
        if (!user) return
        
        // Fetch household
        const { data: h } = await supabase
          .from('households')
          .select('*')
          .eq('admin_id', user.id)
          .maybeSingle()
        
        if (!h) {
          setLoading(false)
          return
        }
        setHousehold(h)

        // Mocking alerts for now based on the pitch deck vision
        // In a real app, these would be generated by an AI background job analyzing 'logs'
        setAlerts([
          {
            id: 1,
            type: 'warning',
            title: 'Participation Drop Detected',
            description: 'Alex\'s chore completion has dropped by 34% this week. This is an early signal of potential imbalance.',
            impact: 'Medium',
            action: 'Suggest Mediation',
            icon: '📉'
          },
          {
            id: 2,
            type: 'insight',
            title: 'Expense Pattern Alert',
            description: 'Groceries spending is 20% higher than last month. It might be time to review the shared budget.',
            impact: 'Low',
            action: 'View Expenses',
            icon: '🛒'
          },
          {
            id: 3,
            type: 'tip',
            title: 'Harmony Suggestion',
            description: 'Everyone has been active this week! A shared meal this weekend could strengthen household bonds.',
            impact: 'Positive',
            action: 'Dismiss',
            icon: '🍕'
          },
          {
            id: 4,
            type: 'critical',
            title: 'Unsettled Imbalance',
            description: 'The expense imbalance has reached ₹450. We recommend settling up before the weekend to maintain clarity.',
            impact: 'High',
            action: 'Settle Up',
            icon: '⚖️'
          }
        ])

      } catch (err) {
        console.error(err)
      } finally {
        setLoading(false)
      }
    }

    fetchData()
  }, [user])

  const getAlertStyles = (type) => {
    switch (type) {
      case 'critical': return 'border-red-500 bg-red-50 text-red-700'
      case 'warning':  return 'border-amber-500 bg-amber-50 text-amber-700'
      case 'insight':  return 'border-blue-500 bg-blue-50 text-blue-700'
      case 'tip':      return 'border-accent-sage bg-green-50 text-green-700'
      default:         return 'border-border-soft bg-white text-dark'
    }
  }

  const getBadgeStyles = (impact) => {
    switch (impact) {
      case 'High':     return 'bg-red-100 text-red-600'
      case 'Medium':   return 'bg-amber-100 text-amber-600'
      case 'Low':      return 'bg-blue-100 text-blue-600'
      case 'Positive': return 'bg-green-100 text-green-600'
      default:         return 'bg-gray-100 text-gray-600'
    }
  }

  if (loading) return (
    <div className="min-h-screen flex items-center justify-center bg-warm-white">
      <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-accent"></div>
    </div>
  )

  return (
    <Layout activeTab="notifications" onNavigate={onNavigate} householdName={household?.name}>
      <div className="max-w-4xl mx-auto space-y-8">
        <div>
          <h2 className="text-xl font-heading font-bold text-dark">Household Alerts & Insights</h2>
          <p className="text-muted text-sm mt-1">AI-powered signals to keep your home running smoothly.</p>
        </div>

        <div className="grid grid-cols-1 gap-6">
          {alerts.length === 0 ? (
            <div className="bg-white p-16 rounded-card text-center shadow-card border-2 border-dashed border-border-soft">
              <p className="text-5xl mb-6">✨</p>
              <h3 className="text-title font-heading font-bold text-dark">All clear!</h3>
              <p className="text-muted max-w-sm mx-auto mt-2">
                No imbalances or alerts detected. Your household is in a state of perfect harmony.
              </p>
            </div>
          ) : (
            alerts.map(alert => (
              <div 
                key={alert.id} 
                className={`flex flex-col md:flex-row items-start md:items-center gap-6 p-6 rounded-card border-l-8 shadow-sm transition-all hover:shadow-md ${getAlertStyles(alert.type)}`}
              >
                <div className="text-4xl bg-white p-3 rounded-soft shadow-sm flex-shrink-0">
                  {alert.icon}
                </div>
                
                <div className="flex-1 space-y-1">
                  <div className="flex items-center gap-3">
                    <h3 className="font-heading font-bold text-dark text-lg">{alert.title}</h3>
                    <span className={`text-[10px] uppercase tracking-widest font-bold px-2 py-0.5 rounded-full ${getBadgeStyles(alert.impact)}`}>
                      {alert.impact} Impact
                    </span>
                  </div>
                  <p className="text-small text-dark-soft leading-relaxed opacity-90">
                    {alert.description}
                  </p>
                </div>

                <div className="flex-shrink-0 w-full md:w-auto pt-4 md:pt-0">
                  <button 
                    onClick={() => {
                      if (alert.action === 'Suggest Mediation') onNavigate('mediation')
                      if (alert.action === 'View Expenses') onNavigate('expenses')
                      // Add other navigations as needed
                    }}
                    className="w-full md:w-auto bg-dark text-white px-6 py-3 rounded-soft font-bold text-xs hover:bg-black transition-all shadow-sm"
                  >
                    {alert.action}
                  </button>
                </div>
              </div>
            ))
          )}
        </div>

        {/* AI Analysis Summary */}
        <div className="bg-white p-8 rounded-card shadow-card border border-border-soft mt-12">
          <div className="flex items-center gap-4 mb-6">
            <div className="w-12 h-12 bg-accent rounded-full flex items-center justify-center text-2xl">🧠</div>
            <div>
              <h3 className="font-heading font-bold text-dark">AI Harmony Analysis</h3>
              <p className="text-xs text-muted">Weekly patterns & sentiment tracking</p>
            </div>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            <div className="space-y-4">
              <h4 className="text-xs uppercase tracking-widest text-muted font-bold">Positive Signals</h4>
              <ul className="space-y-2">
                <li className="text-small flex items-start gap-2">
                  <span className="text-green-500">✓</span>
                  <span>Chore completion rate is above average (85%)</span>
                </li>
                <li className="text-small flex items-start gap-2">
                  <span className="text-green-500">✓</span>
                  <span>Communication in shared areas is constructive</span>
                </li>
              </ul>
            </div>
            <div className="space-y-4">
              <h4 className="text-xs uppercase tracking-widest text-muted font-bold">Growth Areas</h4>
              <ul className="space-y-2">
                <li className="text-small flex items-start gap-2">
                  <span className="text-amber-500">!</span>
                  <span>Weekend activity logging is lower than weekdays</span>
                </li>
                <li className="text-small flex items-start gap-2">
                  <span className="text-amber-500">!</span>
                  <span>One member is bearing 60% of the grocery expenses</span>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </Layout>
  )
}
